dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: JZN4MfYR8B29dS7MI/FPddnqfhRaLidoyzzCfY1OAS7cWn76mWSYpRvpIYAyrQrtqQZAznLJB5MgbFU+60HE2273r+lhI1USi1IwPysh23tOEjMwFcaFEBlYZtlcS4Hj7lrLjjgZhN1TMKvHnNFrkp5SWXed7R0tLXTFSdY49Rb6uY/b96LqPG/l8XfxmEQbXG3Q51QPiioaRpsO+1foXIamUCyJ1HpjnvsHcIpNwFUZrutklZXHslAwxJ7DA9dFGlTxthcGdb0Kx2rNToI0fvKAjJoqr/hstRtsOkOi+wFS8XaHesgAGIWDTy8G4rpMpBMczA5bmbtkyXLOfLj0OXTccGEfQnZRXRC0+8hjWFpcvd9r/FyhZ5OZuCHFub00YBYwBmtOdKn12OROl1UMWtMOyZ2j2QNofjU5Z5Ns1ZWLL/k3Z2XwlhWXo+fKw9MRVlWYUtvuJ1qo6mLdWdqYGV4kj00l3A5Gwpib9cdJxUqU2pV5HvG5Rvcpl1bzLrjMKk5lMghHYy7OQr/FIPZfAMTZuFWmvHLHVW1QzLnAnO3MTMEfgY+jP+dK5NIUigP3gj13AdFkhMaoHkoNm7HxjAMW4B+QrtmqDGcac+UDHeOGNCpq/gD04XgTA9/KudUmt9Eqk9eo2iCywCc40VV9VxdzRFOH03IVpcpe0W5jNB0=
