apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: prom-trickster-memory-stdout
    type: prometheus
    access: proxy
    url: http://trickster:8480/prom1
    isDefault: false
    editable: false
