global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#denis_pirozhkov'
