version: '3'

services:

  fluentd:
    image: souljapanic/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - logging

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - cluster.name=docker-cluster
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - logging

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - logging

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - logging
      - reddit

networks:
  logging:
  reddit:
    external:
      name: reddit
